# Generated by Django 5.1.2 on 2024-11-01 04:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "driver_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("vehicle_details", models.CharField(max_length=255)),
                ("onboarding_date", models.DateTimeField(auto_now_add=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
