# Generated by Django 5.1.2 on 2024-11-07 03:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "driver_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("license_number", models.CharField(max_length=100, unique=True)),
                ("vehicle_details", models.CharField(max_length=255)),
                ("onboarding_date", models.DateTimeField(auto_now_add=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "todays_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "weekly_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monthly_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overall_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("sales_history", models.JSONField(default=dict)),
                ("customers", models.JSONField(default=list)),
                (
                    "target_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_qrcode", models.URLField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
