# Generated by Django 5.1.2 on 2024-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="customers",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="sales_history",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
