# Generated by Django 5.1.2 on 2024-11-03 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "driver",
            "0003_driver_address_driver_date_of_birth_driver_full_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="profile_picture",
        ),
    ]
