# Generated by Django 5.1.2 on 2024-11-08 04:45

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("driver", "0003_alter_driver_user"),
        ("rider", "0005_rider_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ad_link",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="ad_link"
                    ),
                ),
                (
                    "target_country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("show_time_start", models.TimeField(blank=True, null=True)),
                ("show_time_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=100, null=True)),
                ("to_be_viewed_by", models.IntegerField(default=0)),
                ("content", models.TextField(blank=True, null=True)),
                ("numb_views", models.IntegerField(blank=True, default=0, null=True)),
                ("expiration_date", models.DateTimeField(blank=True, null=True)),
                ("custom_link", models.URLField(blank=True, null=True)),
                ("expired", models.BooleanField(blank=True, default=False, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="driver.driver",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to="rider.rider",
                    ),
                ),
                (
                    "viewed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="viewed_ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("reward_given", models.BooleanField(default=False)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.ad"
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_rewards",
                        to="driver.driver",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
