# Generated by Django 5.1.2 on 2024-11-03 21:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
