# Generated by Django 5.1.2 on 2024-11-01 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rider_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("qr_code_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
