# Generated by Django 5.1.2 on 2024-11-07 03:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rider_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("points", models.PositiveIntegerField(default=0)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code_url", models.URLField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "vehicle_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
