# Generated by Django 5.1.2 on 2024-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rider",
            name="rider_id",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
    ]
