# Generated by Django 5.1.2 on 2024-11-03 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rider", "0004_rider_address_rider_date_of_birth_rider_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rider",
            name="profile_picture",
        ),
    ]
