# Generated by Django 5.1.2 on 2024-11-03 15:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_profile_picture_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="profile_picture"
            ),
            preserve_default=False,
        ),
    ]
